* .emacs.d
** Installation
#+begin_src shell
  cd $HOME
  git clone https://github.com/kabu1204/.emacs.d.git
#+end_src
** Feature
This .emacs.d already configures *rust-mode*, *company*, *racer*, *Cider*, *clojure-mode*, *flycheck*, which is mainly for myself to learn **Rust** and **Clojure** .
If you are working with rust or clojure, this is for you.
*** Rust(optional)
Except for cloing this repo, you may also need to:
1. Install Rust
   #+begin_src shell
     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
   #+end_src
2. Install rust crate: racer (which is needed by racer-mode)
   #+begin_src shell
     rustup toolchain add nightly
     rustup default nightly
     cargo install racer
     rustup default stable
     which racer
   #+end_src
   then edit the init.el, probably around *line 101*:
   #+begin_src emacs-lisp
     (setq racer-cmd "what you just get from 'which racer'")
   #+end_src
3. Install rust-src
   #+begin_src shell
     rustup component add rust-src
   #+end_src
4. Configure rust-src path
   This step is not necessary, racer can detect the path automatically.
   #+begin_src shell
     echo $(rustc --print sysroot)/lib/rustlib/src/rust/library
   #+end_src
   then edit the init.el, probably around *line 103*:
   #+begin_src emacs-lisp
     (setq racer-rust-src-path "what you just get by echo")
   #+end_src
**** How to use?
the key-binding is the same as [[https://github.com/racer-rust/emacs-racer#testing-your-setup][emacs-racer#testing-your-setup]]:
1. delay or Press **TAB** for completion
2. move the cursor on a symbol, **M-.** to jump to its definition
   **M-,** to jump back
3. **C-x 4 .** to jump to definition in a new window
   **C-x 5 .** in a new frame

*** Clojure(optional)
Just follow the instruction from [[https://leiningen.org/][Leiningen]] to install lein executable.
